### ISSUE TITLE
Contact Form 7 Plugin shows PHP Notice

### ISSUE THREAD

**Issue by danimalweb** [danimalweb/wp-install#4]
When the plugin is activated the PHP Notice is shown.

This will apply to anything plugins which throw PHP Notices when activated.

We should change the loglevel to ignore Notices.

**Comment by mrchimp** [comment]
Maybe add a `--verbose` flag to leave stuff like that on.

**Comment by danimalweb** [comment]
CF7 removed as a plugin option. I'm quicky moving away from this plugin due to continued security concerns.
